-- Suppression de la table "Accounts" si elle existe
DROP TABLE IF EXISTS LISTGROUPS;
DROP TABLE IF EXISTS MEMBERSGROUPS;
DROP TABLE IF EXISTS CHATSGROUPS;
DROP TABLE IF EXISTS EVENTGROUPS;
DROP TABLE IF EXISTS RESPONSEEVENTGROUPS;